const PWA_VERSION='2026.08.15-pwa2';
let pwaInstallEvent=null,pwaUpdateReady=false;
function pwaToast(text,type=''){let h=document.querySelector('.toast-host');if(!h){h=document.createElement('div');h.className='toast-host';document.body.appendChild(h)}const e=document.createElement('div');e.className=`toast ${type}`;e.textContent=text;h.appendChild(e);setTimeout(()=>e.remove(),4200)}
function pwaStyles(){if(document.getElementById('pwaUxStyle'))return;const s=document.createElement('style');s.id='pwaUxStyle';s.textContent='.pwa-update{position:fixed;z-index:2100;left:12px;right:12px;bottom:calc(92px + env(safe-area-inset-bottom));max-width:620px;margin:0 auto;background:#111827;color:#fff;border:1px solid #344054;border-radius:15px;padding:12px;box-shadow:0 18px 50px rgba(15,23,42,.28);display:flex;gap:12px;align-items:center}.pwa-update-copy{min-width:0;flex:1}.pwa-update-copy strong{display:block;font-size:13px}.pwa-update-copy span{display:block;margin-top:2px;color:#d0d5dd;font-size:11px}.pwa-update-actions{display:flex;gap:7px}.pwa-update button{min-height:40px;border-radius:10px;padding:0 11px;font-size:12px;font-weight:800}.pwa-update-now{border:0;background:#fff;color:#111827}.pwa-update-later{border:1px solid #475467;background:transparent;color:#fff}@media(min-width:760px){.pwa-update{bottom:18px}}@media(max-width:520px){.pwa-update{align-items:stretch;flex-direction:column}.pwa-update-actions button{flex:1;min-height:44px}}';document.head.appendChild(s)}
function pwaInstallButton(){if(!pwaInstallEvent)return;const host=document.querySelector('.topbar-actions');if(!host||host.querySelector('[data-pwa-install]'))return;const b=document.createElement('button');b.type='button';b.className='icon-btn';b.dataset.pwaInstall='1';b.title='Установить приложение';b.setAttribute('aria-label','Установить приложение');b.textContent='⇩';host.prepend(b)}
function pwaUpdateBanner(){if(!pwaUpdateReady||document.querySelector('.pwa-update'))return;pwaStyles();const b=document.createElement('div');b.className='pwa-update';b.setAttribute('role','status');b.setAttribute('aria-live','polite');b.innerHTML='<div class="pwa-update-copy"><strong>Новая версия готова</strong><span>Обновите экран, чтобы использовать последние исправления.</span></div><div class="pwa-update-actions"><button type="button" class="pwa-update-later" data-pwa-later>Позже</button><button type="button" class="pwa-update-now" data-pwa-reload>Обновить</button></div>';document.body.appendChild(b)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();pwaInstallEvent=e;pwaInstallButton()});
window.addEventListener('fleet:ui-ready',()=>{pwaInstallButton();pwaUpdateBanner()});
document.addEventListener('click',async e=>{const install=e.target.closest('[data-pwa-install]');if(install&&pwaInstallEvent){e.preventDefault();const ev=pwaInstallEvent;pwaInstallEvent=null;install.remove();await ev.prompt();const result=await ev.userChoice;if(result?.outcome==='accepted')pwaToast('Автопарк установлен на устройство.','success');return}if(e.target.closest('[data-pwa-reload]')){e.preventDefault();location.reload();return}if(e.target.closest('[data-pwa-later]')){e.preventDefault();document.querySelector('.pwa-update')?.remove();return}},true);
window.addEventListener('appinstalled',()=>{pwaInstallEvent=null;document.querySelector('[data-pwa-install]')?.remove()});
async function registerPwa(){if(!('serviceWorker'in navigator))return;const hadController=Boolean(navigator.serviceWorker.controller);try{const reg=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});if(hadController){navigator.serviceWorker.addEventListener('controllerchange',()=>{if(pwaUpdateReady)return;pwaUpdateReady=true;pwaUpdateBanner()},{once:true})}const check=()=>reg.update().catch(()=>{});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')check()});setInterval(check,15*60*1000);setTimeout(check,2500)}catch(e){console.warn('PWA registration failed',e)}}
pwaStyles();queueMicrotask(pwaInstallButton);registerPwa();
